services:
  jingfaka:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jingfaka7890
      - MYSQL_DATABASE=jingfaka
      - MYSQL_USER=jingfaka
      - MYSQL_PASSWORD=jingfaka7890
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
